services:
  - type: web
    name: twitch-autofarm-dashboard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_DOMAIN
        sync: false # Will be set manually in Render dashboard